# Generated by Django 4.0.4 on 2022-06-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=20)),
                ('st_fname', models.CharField(max_length=200)),
                ('st_lname', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('gender', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
