# Generated by Django 4.0.4 on 2022-07-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_student_address_remove_student_st_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_code', models.CharField(max_length=10)),
                ('dep_name', models.CharField(max_length=20)),
            ],
        ),
    ]
