# Generated by Django 4.0.4 on 2022-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=14)),
                ('credit', models.CharField(max_length=10)),
            ],
        ),
    ]
